name: C++ Style Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (Клонирование репозитория)
        uses: actions/checkout@v2

      - name: Setup C++ Environment (Настройка среды C++)
        run: sudo apt-get install -y clang-format cpplint

      - name: Check Code Style (Проверка стиля кода)
        run: |
          clang-format --version
          cpplint --version
          git diff --name-only --diff-filter=ACMRTUXB ${{ github.event.before }} ${{ github.event.after }} | grep -E "\.(c|cpp|h|hpp)$" | xargs clang-format -i -style=file
          git diff --name-only --diff-filter=ACMRTUXB ${{ github.event.before }} ${{ github.event.after }} | grep -E "\.(c|cpp|h|hpp)$" | xargs cpplint