name: C++ Style Check

on:
  push:
    branches:
      - main

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: cpplint --extensions=h,hpp,cpp --recursive --linelength=120 --filter=-build/include_subdir --output=vs7 .
